### ISSUE TITLE
Leaked input

### ISSUE THREAD

**Issue by Cabbache** [kennysong/micro_smpc#2]
In the multiplication example, couldn't Alice divide the output (-100) by (2 * 5) to find out Bob's input (-10)? I see this as an issue with the function 2 * shared_a * shared_b. Some functions are reversible. Are there ways to "measure" how easily reversible a function is?

**Comment by kennysong** [comment]
You need >2 parties. If there are only two parties, one party can reconstruct the other's input given the output and their own input for arithmetic operations. (This isn't specific to MPC, if you had a trusted third-party doing the computation, it would still be true.)

May be worth adding a note that that example is only supposed to demonstrate the API. Thanks for the question!
