### ISSUE TITLE
URL for PDF download of additive secret sharing requires username/password

### ISSUE THREAD

**Issue by brianblank** [kennysong/micro_smpc#3]
In the README.md file and finite_ring.py file, a URL is referenced for additive secret sharing.  This URL requires an NYU username/password to view.  Is it possible to make this PDF public?

https://cs.nyu.edu/courses/spring07/G22.3033-013/scribe/lecture01.pdf

Thanks.

**Comment by kennysong** [comment]
Unfortunately I don't have a copy of the PDF either. You can try contacting the author of that document: https://cs.nyu.edu/~dodis/#teach

**Comment by brianblank** [comment]
Thanks for your reply. It turns out that I'm a former NYU student and my
account was still active allowing me to access the document.

Thanks.

**Comment by kennysong** [comment]
Great! Glad you could find a copy.
